<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-24 at 13:14:52.
 */
class EventTubeTest extends PHPUnit_Framework_TestCase {

    /**
     * @var EventTube
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new EventTube;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers EventTube::addEvent
     * @todo   Implement testAddEvent().
     */
    public function testAddEvent() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EventTube::addMenu
     * @todo   Implement testAddMenu().
     */
    public function testAddMenu() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EventTube::lockRegion
     * @todo   Implement testLockRegion().
     */
    public function testLockRegion() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EventTube::removeItemFromMenu
     * @todo   Implement testRemoveItemFromMenu().
     */
    public function testRemoveItemFromMenu() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EventTube::clearRegion
     * @todo   Implement testClearRegion().
     */
    public function testClearRegion() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EventTube::getRegion
     * @todo   Implement testGetRegion().
     */
    public function testGetRegion() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EventTube::Debug
     * @todo   Implement testDebug().
     */
    public function testDebug() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
