<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-24 at 13:14:57.
 */
class nodeTreeTest extends PHPUnit_Framework_TestCase {

    /**
     * @var nodeTree
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new nodeTree;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers nodeTree::add
     * @todo   Implement testAdd().
     */
    public function testAdd() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers nodeTree::show
     * @todo   Implement testShow().
     */
    public function testShow() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
