<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-24 at 13:14:47.
 */
class ObjectTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Object
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Object;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Object::setErrorMessage
     * @todo   Implement testSetErrorMessage().
     */
    public function testSetErrorMessage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Object::setSuccessMessage
     * @todo   Implement testSetSuccessMessage().
     */
    public function testSetSuccessMessage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Object::setMessages
     * @todo   Implement testSetMessages().
     */
    public function testSetMessages() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Object::setAlertMessage
     * @todo   Implement testSetAlertMessage().
     */
    public function testSetAlertMessage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Object::setMessage
     * @todo   Implement testSetMessage().
     */
    public function testSetMessage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Object::unsetMessage
     * @todo   Implement testUnsetMessage().
     */
    public function testUnsetMessage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Object::addLog
     * @todo   Implement testAddLog().
     */
    public function testAddLog() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Object::getLog
     * @todo   Implement testGetLog().
     */
    public function testGetLog() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Object::getErrorMessage
     * @todo   Implement testGetErrorMessage().
     */
    public function testGetErrorMessage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Object::getSuccessMessage
     * @todo   Implement testGetSuccessMessage().
     */
    public function testGetSuccessMessage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Object::getAlertMessage
     * @todo   Implement testGetAlertMessage().
     */
    public function testGetAlertMessage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Object::getMessages
     * @todo   Implement testGetMessages().
     */
    public function testGetMessages() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Object::whoAmI
     * @todo   Implement testWhoAmI().
     */
    public function testWhoAmI() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Object::LoadModel
     * @todo   Implement testLoadModel().
     */
    public function testLoadModel() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Object::LoadClassFromPlugin
     * @todo   Implement testLoadClassFromPlugin().
     */
    public function testLoadClassFromPlugin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Object::LoadResource
     * @todo   Implement testLoadResource().
     */
    public function testLoadResource() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Object::LoadData
     * @todo   Implement testLoadData().
     */
    public function testLoadData() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Object::LoadJsPlugin
     * @todo   Implement testLoadJsPlugin().
     */
    public function testLoadJsPlugin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Object::LoadComponent
     * @todo   Implement testLoadComponent().
     */
    public function testLoadComponent() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Object::LoadFile
     * @todo   Implement testLoadFile().
     */
    public function testLoadFile() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Object::LoadConfigFromPlugin
     * @todo   Implement testLoadConfigFromPlugin().
     */
    public function testLoadConfigFromPlugin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Object::LoadConfigFromResource
     * @todo   Implement testLoadConfigFromResource().
     */
    public function testLoadConfigFromResource() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Object::CheckClass
     * @todo   Implement testCheckClass().
     */
    public function testCheckClass() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
