<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-24 at 13:14:57.
 */
class timeResourceTest extends PHPUnit_Framework_TestCase {

    /**
     * @var timeResource
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new timeResource;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers timeResource::getWeedDay
     * @todo   Implement testGetWeedDay().
     */
    public function testGetWeedDay() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers timeResource::diffWeekDay
     * @todo   Implement testDiffWeekDay().
     */
    public function testDiffWeekDay() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers timeResource::absDiffWeekDay
     * @todo   Implement testAbsDiffWeekDay().
     */
    public function testAbsDiffWeekDay() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers timeResource::WeekDay2Int
     * @todo   Implement testWeekDay2Int().
     */
    public function testWeekDay2Int() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers timeResource::diffDate
     * @todo   Implement testDiffDate().
     */
    public function testDiffDate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers timeResource::getFormatedTimestampDiff
     * @todo   Implement testGetFormatedTimestampDiff().
     */
    public function testGetFormatedTimestampDiff() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers timeResource::Timestamp2Time
     * @todo   Implement testTimestamp2Time().
     */
    public function testTimestamp2Time() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers timeResource::addDayIntoDate
     * @todo   Implement testAddDayIntoDate().
     */
    public function testAddDayIntoDate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers timeResource::subDayIntoDate
     * @todo   Implement testSubDayIntoDate().
     */
    public function testSubDayIntoDate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers timeResource::isValidDate
     * @todo   Implement testIsValidDate().
     */
    public function testIsValidDate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers timeResource::isEmptyTime
     * @todo   Implement testIsEmptyTime().
     */
    public function testIsEmptyTime() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers timeResource::Date2StrBr
     * @todo   Implement testDate2StrBr().
     */
    public function testDate2StrBr() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers timeResource::getFormatedDate
     * @todo   Implement testGetFormatedDate().
     */
    public function testGetFormatedDate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers timeResource::getDbDate
     * @todo   Implement testGetDbDate().
     */
    public function testGetDbDate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers timeResource::convert
     * @todo   Implement testConvert().
     */
    public function testConvert() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers timeResource::detectDateType
     * @todo   Implement testDetectDateType().
     */
    public function testDetectDateType() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers timeResource::getTimeOfDate
     * @todo   Implement testGetTimeOfDate().
     */
    public function testGetTimeOfDate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers timeResource::subDateTime
     * @todo   Implement testSubDateTime().
     */
    public function testSubDateTime() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers timeResource::addDateTime
     * @todo   Implement testAddDateTime().
     */
    public function testAddDateTime() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
