<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-24 at 13:15:21.
 */
class menuBuilderTest extends PHPUnit_Framework_TestCase {

    /**
     * @var menuBuilder
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new menuBuilder;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers menuBuilder::setNomePai
     * @todo   Implement testSetNomePai().
     */
    public function testSetNomePai() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers menuBuilder::setMenuId
     * @todo   Implement testSetMenuId().
     */
    public function testSetMenuId() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers menuBuilder::geraMenu
     * @todo   Implement testGeraMenu().
     */
    public function testGeraMenu() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
